FROM node:14.15 as base
WORKDIR /work

COPY . .

RUN npm clean-install
RUN npm run build -- --prod

FROM nginx:alpine

COPY --from=base /work/nginx.conf /etc/nginx/ngnix.conf
COPY --from=base /work/dist/frontEnd/ /usr/share/nginx/html/

EXPOSE 80
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
